import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font" }
size = 14

[window]
opacity = 0.95
option_as_alt = "Both"
